### ISSUE TITLE
ANT fails to detect JDK 1.7

### ISSUE THREAD

**Issue by khayyatzy** [qcri/Qnoise#3]
Hi,

I am trying to compile Qnoise through ant. It says that I am missing JDK 1.7, however the system is already configured with 1.7.0_45. Could it be a problem with build.xml? This is the output of my terminal:
# 

[khayyzy@kw2260 Qnoise-master]$ ant
Buildfile: build.xml

clean:
   [delete] Deleting directory /home/khayyzy/bin/Qnoise-master/out

qnoise:
    [mkdir] Created dir: /home/khayyzy/bin/Qnoise-master/out/production

BUILD FAILED
/home/khayyzy/bin/Qnoise-master/build.xml:74: JDK 1.7 required

Total time: 0 seconds
[khayyzy@kw2260 Qnoise-master]$ which java
~/bin/jdk1.7.0_45/bin/java
[khayyzy@kw2260 Qnoise-master]$ vi ~/.bashrc 
[khayyzy@kw2260 Qnoise-master]$ java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
# Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

**Comment by zyzyis** [comment]
Please paste your javac output?

**Comment by khayyatzy** [comment]
Here you go:

# 

[khayyzy@kw2260 Qnoise-master]$ javac
Usage: javac <options> <source files>
where possible options include:
  -g                         Generate all debugging info
  -g:none                    Generate no debugging info
  -g:{lines,vars,source}     Generate only some debugging info
  -nowarn                    Generate no warnings
  -verbose                   Output messages about what the compiler is doing
  -deprecation               Output source locations where deprecated APIs are used
  -classpath <path>          Specify where to find user class files and annotation processors
  -cp <path>                 Specify where to find user class files and annotation processors
  -sourcepath <path>         Specify where to find input source files
  -bootclasspath <path>      Override location of bootstrap class files
  -extdirs <dirs>            Override location of installed extensions
  -endorseddirs <dirs>       Override location of endorsed standards path
  -proc:{none,only}          Control whether annotation processing and/or compilation is done.
  -processor <class1>[,<class2>,<class3>...] Names of the annotation processors to run; bypasses default discovery process
  -processorpath <path>      Specify where to find annotation processors
  -d <directory>             Specify where to place generated class files
  -s <directory>             Specify where to place generated source files
  -implicit:{none,class}     Specify whether or not to generate class files for implicitly referenced files
  -encoding <encoding>       Specify character encoding used by source files
  -source <release>          Provide source compatibility with specified release
  -target <release>          Generate class files for specific VM version
  -version                   Version information
  -help                      Print a synopsis of standard options
  -Akey[=value]              Options to pass to annotation processors
  -X                         Print a synopsis of nonstandard options
  -J<flag>                   Pass <flag> directly to the runtime system
  -Werror                    Terminate compilation if warnings occur
  @<filename>                Read options and filenames from file

[khayyzy@kw2260 Qnoise-master]$ javac -version
javac 1.7.0_45

#

**Comment by khayyatzy** [comment]
Hi,

Just reinstalled ANT again. It works now thanks!
