### ISSUE TITLE
Multiple column noise & output format

### ISSUE THREAD

**Issue by khayyatzy** [qcri/Qnoise#5]
Hi,

Can we define multiple columns for cell based granularity? I would imagine something like:

"noise" : {
        "noisetype" : "i",
        "granularity" : "cell",
        "percentage" : 0.1,
        "model" : "r",
    "column" : "c_name, c_phone"
    }

I also noticed that the output has extra double quotes character, for example:

Input:
X, 18, f
Y, 87, m
Z, 76, m

Output:
"X"," 18"," f"
"Y"," 87"," m"
"Z","3.0"," m"

Can we generate the output without the extra double quotes character? Thank you

**Comment by ghost** [comment]
This is a good point, we will work on it as the next feature.

Si

**Comment by zyzyis** [comment]
Hi Zuhair,

The commit 1fc847752eab6d6a664170010c25d5ddd85b331c solves the issue.

Si
